version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - "dependencies"
      - "composer"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "11:00"
    labels:
      - "dependencies"
      - "infrastructure"
